workflows:
  default-workflow:
    name: Default Workflow

    environment:
      flutter: stable

    scripts:
      - name: Debug paths
        script: |
          echo "CM_BUILD_DIR = $CM_BUILD_DIR"
          cd $CM_BUILD_DIR
          ls

      - name: Get Flutter packages
        script: |
          cd $CM_BUILD_DIR
          flutter pub get

      - name: Build APK
        script: |
          cd $CM_BUILD_DIR
          flutter build apk --release
